version: '3.1'

services:
  url-shortner:
    image: url-shortner
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_DB: url_shortner_db
      DATABASE_PASSWORD: password
      DB_USERNAME: postgres
    networks:
      - url_shortner_network

networks:
  url_shortner_network:
    name: url_shortner_network
